language: node_js
node_js:
  - "10"
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
before_install: pip install --user awscli
script: make node_modules lint test
before_deploy: cp .npmrc.template $HOME/.npmrc
deploy:
  on:
    branch: master
    tags: true
  provider: script
  script: make release
  skip_cleanup: true
